config/routes.rb
CoMakeIt::Application.routes.draw do
  resources :comake_its

end

app/models/comake_it.rb
class ComakeIt < ActiveRecord::Base
	validates :name, :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comake_its_controller.rb
class ComakeItsController < ApplicationController
  before_action :set_comake_it, only: [:show, :edit, :update, :destroy]

  # GET /comake_its
  # GET /comake_its.json
  def index
    @comake_its = ComakeIt.all
  end

  # GET /comake_its/1
  # GET /comake_its/1.json
  def show
  end

  # GET /comake_its/new
  def new
    @comake_it = ComakeIt.new
  end

  # GET /comake_its/1/edit
  def edit
  end

  # POST /comake_its
  # POST /comake_its.json
  def create
    @comake_it = ComakeIt.new(comake_it_params)

    respond_to do |format|
      if @comake_it.save
        format.html { redirect_to @comake_it, notice: 'Comake it was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comake_it }
      else
        format.html { render action: 'new' }
        format.json { render json: @comake_it.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comake_its/1
  # PATCH/PUT /comake_its/1.json
  def update
    respond_to do |format|
      if @comake_it.update(comake_it_params)
        format.html { redirect_to @comake_it, notice: 'Comake it was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comake_it.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comake_its/1
  # DELETE /comake_its/1.json
  def destroy
    @comake_it.destroy
    respond_to do |format|
      format.html { redirect_to comake_its_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comake_it
      @comake_it = ComakeIt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comake_it_params
      params.require(:comake_it).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comake_its_helper.rb
module ComakeItsHelper
end

app/views/comake_its/_form.html.erb
<%= form_for(@comake_it) do |f| %>
  <% if @comake_it.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comake_it.errors.count, "error") %> prohibited this comake_it from being saved:</h2>

      <ul>
      <% @comake_it.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comake_its/edit.html.erb
<h1>Editing comake_it</h1>

<%= render 'form' %>

<%= link_to 'Show', @comake_it %> |
<%= link_to 'Back', comake_its_path %>

app/views/comake_its/index.html.erb
<h1>Listing comake_its</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comake_its.each do |comake_it| %>
      <tr>
        <td><%= comake_it.name %></td>
        <td><%= comake_it.email %></td>
        <td><%= comake_it.password %></td>
        <td><%= link_to 'Show', comake_it %></td>
        <td><%= link_to 'Edit', edit_comake_it_path(comake_it) %></td>
        <td><%= link_to 'Destroy', comake_it, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comake it', new_comake_it_path %>

app/views/comake_its/new.html.erb
<h1>New comake_it</h1>

<%= render 'form' %>

<%= link_to 'Back', comake_its_path %>

app/views/comake_its/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comake_it.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @comake_it.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @comake_it.password %>
</p>

<%= link_to 'Edit', edit_comake_it_path(@comake_it) %> |
<%= link_to 'Back', comake_its_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoMakeIt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>